*&---------------------------------------------------------------------*
*& Include          ZMM_MATERIAL_MAINTENANCE_S01
*&---------------------------------------------------------------------*
"Selection Screen
SELECTION-SCREEN BEGIN OF BLOCK b1.
  SELECTION-SCREEN PUSHBUTTON /2(25) p_btn USER-COMMAND btn_clk.
  SELECTION-SCREEN SKIP.
SELECTION-SCREEN END OF BLOCK b1.
SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-001.
  PARAMETERS : r_local RADIOBUTTON GROUP rbg1 DEFAULT 'X' USER-COMMAND ucmd,
               p_file1 TYPE string LOWER CASE DEFAULT TEXT-002 MODIF ID md1,
               r_unix  RADIOBUTTON GROUP rbg1,
               p_file2 TYPE string LOWER CASE DEFAULT TEXT-003 MODIF ID md2.
SELECTION-SCREEN END OF BLOCK b2.
SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE TEXT-004.
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS : r_create RADIOBUTTON GROUP rbg2 DEFAULT 'X' USER-COMMAND ucmd.
    SELECTION-SCREEN COMMENT 3(7) TEXT-r01.
    SELECTION-SCREEN POSITION 12.
    PARAMETERS : r_update RADIOBUTTON GROUP rbg2.
    SELECTION-SCREEN COMMENT 14(7) TEXT-r02.
    SELECTION-SCREEN POSITION 22.
    PARAMETERS : r_extend RADIOBUTTON GROUP rbg2.
    SELECTION-SCREEN COMMENT 24(7) TEXT-r03.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN SKIP 1.
  PARAMETERS : p_mtart  TYPE mtart AS LISTBOX VISIBLE LENGTH 10 USER-COMMAND ucmd,
               p_indsec TYPE char1 AS LISTBOX VISIBLE LENGTH 4 USER-COMMAND ucmd,
               p_busprf TYPE char20 AS LISTBOX VISIBLE LENGTH 20 USER-COMMAND ucmd,
               p_sales  AS CHECKBOX DEFAULT 'X',
               p_class    AS CHECKBOX DEFAULT 'X',
               p_purch   AS CHECKBOX DEFAULT 'X',
               p_mrp    AS CHECKBOX DEFAULT 'X',
               p_plnst  AS CHECKBOX DEFAULT 'X',
               p_val   AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK b3.
SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME TITLE TEXT-005.
  PARAMETERS : p_file3 TYPE string LOWER CASE DEFAULT TEXT-006 MODIF ID md3,
               p_email TYPE ad_smtpadr DEFAULT TEXT-008 MODIF ID md3,
               p_test  AS CHECKBOX DEFAULT abap_true USER-COMMAND ucmd.
SELECTION-SCREEN END OF BLOCK b4.
